/*++

Copyright (c) 1998  Intel Corporation

Module Name:

    math.c

Abstract:




Revision History

--*/

#include "lib.h"


UINT64
LShiftU64 (
    IN UINT64   Operand,
    IN UINTN    Count
    )
// Left shift 64bit by 32bit and get a 64bit result
{
#ifdef __GNUC__
    return Operand << Count;
#else
    UINT64      Result;
    _asm {
        mov     eax, dword ptr Operand[0]
        mov     edx, dword ptr Operand[4]
        mov     ecx, Count
        and     ecx, 63

        shld    edx, eax, cl
        shl     eax, cl

        cmp     ecx, 32
        jc      short ls10

        mov     edx, eax
        xor     eax, eax

ls10:
        mov     dword ptr Result[0], eax
        mov     dword ptr Result[4], edx
    }

    return Result;
#endif
}

UINT64
RShiftU64 (
    IN UINT64   Operand,
    IN UINTN    Count
    )
// Right shift 64bit by 32bit and get a 64bit result
{
#ifdef __GNUC__
    return Operand >> Count;
#else
    UINT64      Result;
    _asm {
        mov     eax, dword ptr Operand[0]
        mov     edx, dword ptr Operand[4]
        mov     ecx, Count
        and     ecx, 63

        shrd    eax, edx, cl
        shr     edx, cl

        cmp     ecx, 32
        jc      short rs10

        mov     eax, edx
        xor     edx, edx

rs10:
        mov     dword ptr Result[0], eax
        mov     dword ptr Result[4], edx
    }

    return Result;
#endif
}


UINT64
MultU64x32 (
    IN UINT64   Multiplicand,
    IN UINTN    Multiplier
    )
// Multiple 64bit by 32bit and get a 64bit result
{
#ifdef __GNUC__
    return Multiplicand * Multiplier;
#else
    UINT64      Result;
    _asm {
        mov     eax, dword ptr Multiplicand[0]
        mul     Multiplier
        mov     dword ptr Result[0], eax
        mov     dword ptr Result[4], edx
        mov     eax, dword ptr Multiplicand[4]
        mul     Multiplier
        add     dword ptr Result[4], eax
    }

    return Result;
#endif
}

UINT64
DivU64x32 (
    IN UINT64   Dividend,
    IN UINTN    Divisor,
    OUT UINTN   *Remainder OPTIONAL
    )
// divide 64bit by 32bit and get a 64bit result
// N.B. only works for 31bit divisors!!
{
#if 0 && defined(__GNUC__) && !defined(__MINGW32__)
    if (Remainder)
        *Remainder = Dividend % Divisor;
    return Dividend / Divisor;
#else
    UINT32      Rem;
    UINT32      bit;

    ASSERT (Divisor != 0);
    ASSERT ((Divisor >> 31) == 0);

    //
    // For each bit in the dividend
    //

    Rem = 0;
    for (bit=0; bit < 64; bit++) {
#if defined(__GNUC__) || defined(__MINGW32__)
        __asm__ (
            "shll	$1, %0\n\t"
            "rcll	$1, 4%0\n\t"
            "rcll	$1, %2\n\t"
            "mov	%2, %%eax\n\t"
            "cmp	%1, %%eax\n\t"
            "cmc\n\t"
            "sbb	%%eax, %%eax\n\t"
            "sub	%%eax, %0\n\t"
            "and	%1, %%eax\n\t"
            "sub	%%eax, %2"
            : /* no outputs */
            : "m"(Dividend), "m"(Divisor), "m"(Rem)
            : "cc","memory","%eax"
            );
#else
        _asm {
            shl     dword ptr Dividend[0], 1    ; shift rem:dividend left one
            rcl     dword ptr Dividend[4], 1
            rcl     dword ptr Rem, 1

            mov     eax, Rem
            cmp     eax, Divisor                ; Is Rem >= Divisor?
            cmc                                 ; No - do nothing
            sbb     eax, eax                    ; Else,
            sub     dword ptr Dividend[0], eax  ;   set low bit in dividen
            and     eax, Divisor                ; and
            sub     Rem, eax                    ;   subtract divisor
        }
#endif
    }

    if (Remainder) {
        *Remainder = Rem;
    }

    return Dividend;
#endif
}

// gcc on IA32 emits these calls on i64 division, as it expects linking with libgcc
// NB: The assembly code was generated by Claude.
#if defined(__GNUC__) && defined(__MINGW32__)
__attribute__ ((__used__))
long long
__divmoddi4(
  long long dividend,
  long long divisor,
  long long *remainder
  )
{
    long long quot, rem;
    int cnt;

    __asm__ (
        // eax/edx = |dividend|  (becomes quotient), ecx/ebx = |divisor|
        "movl   %[n], %%eax          \n\t"
        "movl   %H[n], %%edx         \n\t"
        "movl   %[d], %%ecx          \n\t"
        "movl   %H[d], %%ebx         \n\t"

        "testl  %%edx, %%edx         \n\t"
        "jns    1f                   \n\t"
        "negl   %%edx                \n\t"
        "negl   %%eax                \n\t"
        "sbbl   $0, %%edx            \n\t"
        "1:                          \n\t"
        "testl  %%ebx, %%ebx         \n\t"
        "jns    2f                   \n\t"
        "negl   %%ebx                \n\t"
        "negl   %%ecx                \n\t"
        "sbbl   $0, %%ebx            \n\t"
        "2:                          \n\t"

        // edi:esi = running remainder = 0
        "xorl   %%esi, %%esi         \n\t"
        "xorl   %%edi, %%edi         \n\t"
        "movl   $64, %[c]            \n\t"

        // shift-subtract loop
        "3:                          \n\t"
        "shll   $1, %%eax            \n\t"
        "rcll   $1, %%edx            \n\t"
        "rcll   $1, %%esi            \n\t"
        "rcll   $1, %%edi            \n\t"
        "cmpl   %%ebx, %%edi         \n\t"   // remainder >= divisor?
        "jb     4f                   \n\t"
        "ja     5f                   \n\t"
        "cmpl   %%ecx, %%esi         \n\t"
        "jb     4f                   \n\t"
        "5:                          \n\t"
        "subl   %%ecx, %%esi         \n\t"
        "sbbl   %%ebx, %%edi         \n\t"
        "orl    $1, %%eax            \n\t"
        "4:                          \n\t"
        "decl   %[c]                 \n\t"
        "jnz    3b                   \n\t"

        // sign fixup: quotient negative if signs differ,
        // remainder takes the sign of the dividend
        "movl   %H[n], %%ebx         \n\t"
        "movl   %H[d], %%ecx         \n\t"
        "xorl   %%ebx, %%ecx         \n\t"
        "jns    6f                   \n\t"
        "negl   %%edx                \n\t"
        "negl   %%eax                \n\t"
        "sbbl   $0, %%edx            \n\t"
        "6:                          \n\t"
        "testl  %%ebx, %%ebx         \n\t"
        "jns    7f                   \n\t"
        "negl   %%edi                \n\t"
        "negl   %%esi                \n\t"
        "sbbl   $0, %%edi            \n\t"
        "7:                          \n\t"

        // store results
        "movl   %%eax, %[q]          \n\t"
        "movl   %%edx, %H[q]         \n\t"
        "movl   %%esi, %[r]          \n\t"
        "movl   %%edi, %H[r]         \n\t"
        : [q] "=&m" (quot), [r] "=&m" (rem), [c] "=&m" (cnt)
        : [n] "m" (dividend), [d] "m" (divisor)
        : "eax", "ebx", "ecx", "edx", "esi", "edi", "cc"
            );

    if (remainder)
        *remainder = rem;
    return quot;
}

__attribute__ ((__used__))
long long
__divdi3(
    long long dividend,
    long long divisor
    )
{
    return __divmoddi4(dividend, divisor, 0);
}

long long
__moddi3(
    long long dividend,
    long long divisor
    )
{
    long long rem;
    __divmoddi4(dividend, divisor, &rem);
    return rem;
}
#endif